# Generated by Django 4.1.4 on 2022-12-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="admin", managers=[],),
        migrations.AlterModelManagers(name="teacher", managers=[],),
    ]
