version: '3.3'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "14000:6379"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
